spring:
  application:
    name: hot-list-java
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  rabbitmq:
    host: 127.0.0.1
    listener:
      simple:
        acknowledge-mode: manual #手动ack
      virtual-host: /hot
server:
  port: 8081
token:
  privateKey: '1asd]uft87i3r,mnIO&^DF(@#'
